name: cinemawala
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  share: ^2.0.4
  flutter_icons: ^1.1.0
  table_calendar: ^2.3.3
  cached_network_image: ^3.1.0
  carousel_pro: ^1.0.0
  pdf: ^3.4.2
  firebase_auth: ^3.0.2
  image_picker: ^0.8.3+2
  firebase_core: ^1.5.0
  ext_storage: 1.0.3
  universal_html: ^2.0.8
  permission_handler: ^8.1.4+2
  country_code_picker: ^2.0.2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter


  cupertino_icons:
  file_picker: ^3.0.2+2
  image_picker_web: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
    - family: BalooTammudu2
      fonts:
        - asset: fonts/BalooTammudu2-Regular.ttf
        - asset: fonts/BalooTammudu2-Bold.ttf
          weight: 600
        - asset: fonts/BalooTammudu2-ExtraBold.ttf
          weight: 800

  assets:
    - assets/images/